### ISSUE TITLE
How to achieve this color scheme & accent? 

### ISSUE THREAD

**Issue by ni554n** [oivva/otto#39]
## Trying to achieve:
![otto](http://i.imgur.com/XwbQCDS.png)
## So far:
![mine](http://i.imgur.com/xIlSVnH.png)

**Comment by oivva** [comment]
Color scheme differs because of syntax that you use for `Preferences.sublime-settings` (JSON, should be Sublime Settings).

Possible solution:
1. Open **`Preferences.sublime-settings`**
2. Then go to  menu item: **`Sublime Text -> Preferences -> Settings - More -> Syntax Specific - User`**
3. Remove **`"sublime-theme"`** from extensions section in **`JSON.sublime-settings`**

P.S. Anyway JSON highlighting will be much better starting next 2.0.0 release.

**Comment by ni554n** [comment]
I'm seeing a shade / divider between the tab and the editor window. But your setup has more unified look. How do I achieve that? And the orange accent is bit more saturated than default orange. Why is that?

**Comment by oivva** [comment]
Sorry, you can't do this right now. Because *unified look* is just gif recording artifacts. Now only selected tab has the same background as the editor window by default. I have plans to implement "one color" mode, but it will be not earlier than 2.1.0. Orange and purple accents will be reviewed in the 2.0.0. 

> I'm seeing a shade / divider between the tab and the editor window. 
I think it's something not theme related, because there is no styles for that.

**Comment by ni554n** [comment]
Thanks for clarifying. Beautiful theme by the way.
